#!/usr/bin/python3
from singly_linked_list import SinglyLinkedList

sll = SinglyLinkedList()
sll.add_node_end("0")
sll.add_node_end("2")
sll.add_node_end("4")
sll.add_node_end("8")
sll.add_node_end("16")
sll.add_node_end("32")
sll.add_node_end("64")
sll.add_node_end("128")
sll.add_node_end("256")
sll.add_node_end("512")
sll.add_node_end("1024")
sll.add_node_end("2048")
sll.print_list()
print("------------------")
print(sll.pop_list())
print("------------------")
sll.print_list()
print("------------------")
sll.reverse_list()
sll.print_list()
print("------------------")
sll.reverse_list()
sll.add_node("new head")
sll.print_list()
print("------------------")
sll.pop_list()
print(sll.get_node(1))
print("------------------")
sll.insert_node(5, "inserted node")
sll.print_list()
print("------------------")
sll.delete_node(5)
sll.print_list()
print("------------------")
